<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: proto/rawAd.proto

namespace Ad;

use Grpc\BaseStub;

class RawAdClient extends BaseStub
{

    public function __construct($hostname, $opts, $channel = null) {
        try {
            parent::__construct($hostname, $opts, $channel);
        } catch (\Exception $e) {
        }
    }

    /**
     * rpc SayTest(TestRequest) returns (TestReply) {}
     * 方法名尽量和 (gprc 定义 Xuexitest 服务)的方法一样
     * 用于请求和响应该服务
     */
    /**
     * @param RequestUser $argument
     * @param array       $metadata
     * @param array       $options
     * @return \Grpc\UnaryCall
     */
    public function Query(\Ad\Request $request, $metadata = [], $options = [])
    {
        return $this->_simpleRequest(
            '/ad.RawAd/Query',
            $request,
            ['\Ad\Reply', 'decode'],
            $metadata,
            $options
        );
    }

    public function GlobalQuery(\Ad\Request $request, $metadata = [], $options = [])
    {
        return $this->_simpleRequest(
            '/ad.RawAd/GlobalQuery',
            $request,
            ['\Ad\GlobalReply', 'decode'],
            $metadata,
            $options
        );
    }

    public function AllianceQuery(\Ad\Request $request, $metadata = [], $options = [])
    {
        return $this->_simpleRequest(
            '/ad.RawAd/AllianceQuery',
            $request,
            ['\Ad\AllianceReply', 'decode'],
            $metadata,
            $options
        );
    }
}

