<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use UnexpectedValueException;

/**
 * Protobuf type <code>ad.AdFrom</code>
 */
class AdFrom
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_ADFROM = 0;</code>
     */
    const UNKNOWN_ADFROM = 0;
    /**
     * Generated from protobuf enum <code>BAIDU = 1;</code>
     */
    const BAIDU = 1;
    /**
     * Generated from protobuf enum <code>GOOGLE = 2;</code>
     */
    const GOOGLE = 2;
    /**
     * Generated from protobuf enum <code>TOUTIAO = 3;</code>
     */
    const TOUTIAO = 3;
    /**
     * Generated from protobuf enum <code>INVENO = 4;</code>
     */
    const INVENO = 4;
    /**
     * Generated from protobuf enum <code>GUANGDIANTONG = 5;</code>
     */
    const GUANGDIANTONG = 5;
    /**
     * Generated from protobuf enum <code>BAIDU_HYBRID = 6;</code>
     */
    const BAIDU_HYBRID = 6;
    /**
     * Generated from protobuf enum <code>KEDAXUNFEI = 7;</code>
     */
    const KEDAXUNFEI = 7;
    /**
     * Generated from protobuf enum <code>INMOBI = 8;</code>
     */
    const INMOBI = 8;

    private static $valueToName = [
        self::UNKNOWN_ADFROM => 'UNKNOWN_ADFROM',
        self::BAIDU => 'BAIDU',
        self::GOOGLE => 'GOOGLE',
        self::TOUTIAO => 'TOUTIAO',
        self::INVENO => 'INVENO',
        self::GUANGDIANTONG => 'GUANGDIANTONG',
        self::BAIDU_HYBRID => 'BAIDU_HYBRID',
        self::KEDAXUNFEI => 'KEDAXUNFEI',
        self::INMOBI => 'INMOBI',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

