<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *联盟广告返回体
 *
 * Generated from protobuf message <code>ad.AllianceReply</code>
 */
class AllianceReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .ad.AllianceAdObject alliance_data = 1;</code>
     */
    private $alliance_data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ad\AllianceAdObject[]|\Google\Protobuf\Internal\RepeatedField $alliance_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RawAd::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .ad.AllianceAdObject alliance_data = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAllianceData()
    {
        return $this->alliance_data;
    }

    /**
     * Generated from protobuf field <code>repeated .ad.AllianceAdObject alliance_data = 1;</code>
     * @param \Ad\AllianceAdObject[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAllianceData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ad\AllianceAdObject::class);
        $this->alliance_data = $arr;

        return $this;
    }

}

