<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 联盟广告
 *
 * Generated from protobuf message <code>ad.AllianceAdObject</code>
 */
class AllianceAdObject extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ad_id = 1;</code>
     */
    private $ad_id = '';
    /**
     * Generated from protobuf field <code>string ad_name = 2;</code>
     */
    private $ad_name = '';
    /**
     * Generated from protobuf field <code>string order_id = 3;</code>
     */
    private $order_id = '';
    /**
     * Generated from protobuf field <code>.ad.Information information = 4;</code>
     */
    private $information = 0;
    /**
     * Generated from protobuf field <code>repeated .ad.TimeObject time = 7;</code>
     */
    private $time;
    /**
     * Generated from protobuf field <code>.ad.MPlay m_play = 10;</code>
     */
    private $m_play = 0;
    /**
     * Generated from protobuf field <code>repeated int32 provinces = 11 [packed = true];</code>
     */
    private $provinces;
    /**
     * Generated from protobuf field <code>float bidding = 16;</code>
     */
    private $bidding = 0.0;
    /**
     * Generated from protobuf field <code>.ad.Distribution plan_hour_type = 20;</code>
     */
    private $plan_hour_type = 0;
    /**
     * Generated from protobuf field <code>.ad.CreateType create_type = 21;</code>
     */
    private $create_type = 0;
    /**
     * Generated from protobuf field <code>.ad.AdFrom ad_from = 22;</code>
     */
    private $ad_from = 0;
    /**
     * Generated from protobuf field <code>.ad.JumpType jump_type = 23;</code>
     */
    private $jump_type = 0;
    /**
     * Generated from protobuf field <code>string union_ad_place_id = 25;</code>
     */
    private $union_ad_place_id = '';
    /**
     * Generated from protobuf field <code>string union_ad_js = 26;</code>
     */
    private $union_ad_js = '';
    /**
     * Generated from protobuf field <code>int32 union_ad_width = 27;</code>
     */
    private $union_ad_width = 0;
    /**
     * Generated from protobuf field <code>int32 union_ad_height = 28;</code>
     */
    private $union_ad_height = 0;
    /**
     * Generated from protobuf field <code>int32 advertiser_id = 37;</code>
     */
    private $advertiser_id = 0;
    /**
     * Generated from protobuf field <code>string payment = 47;</code>
     */
    private $payment = '';
    /**
     * Generated from protobuf field <code>int32 position = 50;</code>
     */
    private $position = 0;
    /**
     * Generated from protobuf field <code>.ad.PlatformType platform_type = 51;</code>
     */
    private $platform_type = 0;
    /**
     * Generated from protobuf field <code>int32 cpm_num = 52;</code>
     */
    private $cpm_num = 0;
    /**
     * Generated from protobuf field <code>int32 click_num = 53;</code>
     */
    private $click_num = 0;
    /**
     * Generated from protobuf field <code>map<string, string> annotations = 56;</code>
     */
    private $annotations;
    /**
     * Generated from protobuf field <code>int64 ad_budget = 62;</code>
     */
    private $ad_budget = 0;
    /**
     * Generated from protobuf field <code>string union_app_id = 64;</code>
     */
    private $union_app_id = '';
    /**
     * Generated from protobuf field <code>int32 union_alliance_type = 65;</code>
     */
    private $union_alliance_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ad_id
     *     @type string $ad_name
     *     @type string $order_id
     *     @type int $information
     *     @type \Ad\TimeObject[]|\Google\Protobuf\Internal\RepeatedField $time
     *     @type int $m_play
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $provinces
     *     @type float $bidding
     *     @type int $plan_hour_type
     *     @type int $create_type
     *     @type int $ad_from
     *     @type int $jump_type
     *     @type string $union_ad_place_id
     *     @type string $union_ad_js
     *     @type int $union_ad_width
     *     @type int $union_ad_height
     *     @type int $advertiser_id
     *     @type string $payment
     *     @type int $position
     *     @type int $platform_type
     *     @type int $cpm_num
     *     @type int $click_num
     *     @type array|\Google\Protobuf\Internal\MapField $annotations
     *     @type int|string $ad_budget
     *     @type string $union_app_id
     *     @type int $union_alliance_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RawAd::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ad_id = 1;</code>
     * @return string
     */
    public function getAdId()
    {
        return $this->ad_id;
    }

    /**
     * Generated from protobuf field <code>string ad_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAdId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ad_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ad_name = 2;</code>
     * @return string
     */
    public function getAdName()
    {
        return $this->ad_name;
    }

    /**
     * Generated from protobuf field <code>string ad_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAdName($var)
    {
        GPBUtil::checkString($var, True);
        $this->ad_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_id = 3;</code>
     * @return string
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     * Generated from protobuf field <code>string order_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ad.Information information = 4;</code>
     * @return int
     */
    public function getInformation()
    {
        return $this->information;
    }

    /**
     * Generated from protobuf field <code>.ad.Information information = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setInformation($var)
    {
        GPBUtil::checkEnum($var, \Ad\Information::class);
        $this->information = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ad.TimeObject time = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>repeated .ad.TimeObject time = 7;</code>
     * @param \Ad\TimeObject[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTime($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ad\TimeObject::class);
        $this->time = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ad.MPlay m_play = 10;</code>
     * @return int
     */
    public function getMPlay()
    {
        return $this->m_play;
    }

    /**
     * Generated from protobuf field <code>.ad.MPlay m_play = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setMPlay($var)
    {
        GPBUtil::checkEnum($var, \Ad\MPlay::class);
        $this->m_play = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 provinces = 11 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProvinces()
    {
        return $this->provinces;
    }

    /**
     * Generated from protobuf field <code>repeated int32 provinces = 11 [packed = true];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProvinces($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->provinces = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float bidding = 16;</code>
     * @return float
     */
    public function getBidding()
    {
        return $this->bidding;
    }

    /**
     * Generated from protobuf field <code>float bidding = 16;</code>
     * @param float $var
     * @return $this
     */
    public function setBidding($var)
    {
        GPBUtil::checkFloat($var);
        $this->bidding = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ad.Distribution plan_hour_type = 20;</code>
     * @return int
     */
    public function getPlanHourType()
    {
        return $this->plan_hour_type;
    }

    /**
     * Generated from protobuf field <code>.ad.Distribution plan_hour_type = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setPlanHourType($var)
    {
        GPBUtil::checkEnum($var, \Ad\Distribution::class);
        $this->plan_hour_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ad.CreateType create_type = 21;</code>
     * @return int
     */
    public function getCreateType()
    {
        return $this->create_type;
    }

    /**
     * Generated from protobuf field <code>.ad.CreateType create_type = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setCreateType($var)
    {
        GPBUtil::checkEnum($var, \Ad\CreateType::class);
        $this->create_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ad.AdFrom ad_from = 22;</code>
     * @return int
     */
    public function getAdFrom()
    {
        return $this->ad_from;
    }

    /**
     * Generated from protobuf field <code>.ad.AdFrom ad_from = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setAdFrom($var)
    {
        GPBUtil::checkEnum($var, \Ad\AdFrom::class);
        $this->ad_from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ad.JumpType jump_type = 23;</code>
     * @return int
     */
    public function getJumpType()
    {
        return $this->jump_type;
    }

    /**
     * Generated from protobuf field <code>.ad.JumpType jump_type = 23;</code>
     * @param int $var
     * @return $this
     */
    public function setJumpType($var)
    {
        GPBUtil::checkEnum($var, \Ad\JumpType::class);
        $this->jump_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string union_ad_place_id = 25;</code>
     * @return string
     */
    public function getUnionAdPlaceId()
    {
        return $this->union_ad_place_id;
    }

    /**
     * Generated from protobuf field <code>string union_ad_place_id = 25;</code>
     * @param string $var
     * @return $this
     */
    public function setUnionAdPlaceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->union_ad_place_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string union_ad_js = 26;</code>
     * @return string
     */
    public function getUnionAdJs()
    {
        return $this->union_ad_js;
    }

    /**
     * Generated from protobuf field <code>string union_ad_js = 26;</code>
     * @param string $var
     * @return $this
     */
    public function setUnionAdJs($var)
    {
        GPBUtil::checkString($var, True);
        $this->union_ad_js = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 union_ad_width = 27;</code>
     * @return int
     */
    public function getUnionAdWidth()
    {
        return $this->union_ad_width;
    }

    /**
     * Generated from protobuf field <code>int32 union_ad_width = 27;</code>
     * @param int $var
     * @return $this
     */
    public function setUnionAdWidth($var)
    {
        GPBUtil::checkInt32($var);
        $this->union_ad_width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 union_ad_height = 28;</code>
     * @return int
     */
    public function getUnionAdHeight()
    {
        return $this->union_ad_height;
    }

    /**
     * Generated from protobuf field <code>int32 union_ad_height = 28;</code>
     * @param int $var
     * @return $this
     */
    public function setUnionAdHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->union_ad_height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 advertiser_id = 37;</code>
     * @return int
     */
    public function getAdvertiserId()
    {
        return $this->advertiser_id;
    }

    /**
     * Generated from protobuf field <code>int32 advertiser_id = 37;</code>
     * @param int $var
     * @return $this
     */
    public function setAdvertiserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->advertiser_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payment = 47;</code>
     * @return string
     */
    public function getPayment()
    {
        return $this->payment;
    }

    /**
     * Generated from protobuf field <code>string payment = 47;</code>
     * @param string $var
     * @return $this
     */
    public function setPayment($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 position = 50;</code>
     * @return int
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Generated from protobuf field <code>int32 position = 50;</code>
     * @param int $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkInt32($var);
        $this->position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ad.PlatformType platform_type = 51;</code>
     * @return int
     */
    public function getPlatformType()
    {
        return $this->platform_type;
    }

    /**
     * Generated from protobuf field <code>.ad.PlatformType platform_type = 51;</code>
     * @param int $var
     * @return $this
     */
    public function setPlatformType($var)
    {
        GPBUtil::checkEnum($var, \Ad\PlatformType::class);
        $this->platform_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cpm_num = 52;</code>
     * @return int
     */
    public function getCpmNum()
    {
        return $this->cpm_num;
    }

    /**
     * Generated from protobuf field <code>int32 cpm_num = 52;</code>
     * @param int $var
     * @return $this
     */
    public function setCpmNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->cpm_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 click_num = 53;</code>
     * @return int
     */
    public function getClickNum()
    {
        return $this->click_num;
    }

    /**
     * Generated from protobuf field <code>int32 click_num = 53;</code>
     * @param int $var
     * @return $this
     */
    public function setClickNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->click_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> annotations = 56;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAnnotations()
    {
        return $this->annotations;
    }

    /**
     * Generated from protobuf field <code>map<string, string> annotations = 56;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAnnotations($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->annotations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ad_budget = 62;</code>
     * @return int|string
     */
    public function getAdBudget()
    {
        return $this->ad_budget;
    }

    /**
     * Generated from protobuf field <code>int64 ad_budget = 62;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAdBudget($var)
    {
        GPBUtil::checkInt64($var);
        $this->ad_budget = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string union_app_id = 64;</code>
     * @return string
     */
    public function getUnionAppId()
    {
        return $this->union_app_id;
    }

    /**
     * Generated from protobuf field <code>string union_app_id = 64;</code>
     * @param string $var
     * @return $this
     */
    public function setUnionAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->union_app_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 union_alliance_type = 65;</code>
     * @return int
     */
    public function getUnionAllianceType()
    {
        return $this->union_alliance_type;
    }

    /**
     * Generated from protobuf field <code>int32 union_alliance_type = 65;</code>
     * @param int $var
     * @return $this
     */
    public function setUnionAllianceType($var)
    {
        GPBUtil::checkInt32($var);
        $this->union_alliance_type = $var;

        return $this;
    }

}

