<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *通知PHP预算消耗完了
 *
 * Generated from protobuf message <code>ad.CallbackServiceRequest</code>
 */
class CallbackServiceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ad_id = 1;</code>
     */
    private $ad_id = '';
    /**
     * Generated from protobuf field <code>string slot_binding = 2;</code>
     */
    private $slot_binding = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ad_id
     *     @type string $slot_binding
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RawAd::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ad_id = 1;</code>
     * @return string
     */
    public function getAdId()
    {
        return $this->ad_id;
    }

    /**
     * Generated from protobuf field <code>string ad_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAdId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ad_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string slot_binding = 2;</code>
     * @return string
     */
    public function getSlotBinding()
    {
        return $this->slot_binding;
    }

    /**
     * Generated from protobuf field <code>string slot_binding = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSlotBinding($var)
    {
        GPBUtil::checkString($var, True);
        $this->slot_binding = $var;

        return $this;
    }

}

