<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

if (false) {
    /**
     * This class is deprecated. Use Ad\CreativeObject\Materials instead.
     * @deprecated
     */
    class CreativeObject_Materials {}
}
class_exists(CreativeObject\Materials::class);
@trigger_error('Ad\CreativeObject_Materials is deprecated and will be removed in the next major release. Use Ad\CreativeObject\Materials instead', E_USER_DEPRECATED);

