<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use UnexpectedValueException;

/**
 *流量类型
 *
 * Protobuf type <code>ad.FlowType</code>
 */
class FlowType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_FLOWTYPE = 0;</code>
     */
    const UNKNOWN_FLOWTYPE = 0;
    /**
     * Generated from protobuf enum <code>FLOWTYPE_APP = 1;</code>
     */
    const FLOWTYPE_APP = 1;
    /**
     * Generated from protobuf enum <code>FLOWTYPE_PC = 2;</code>
     */
    const FLOWTYPE_PC = 2;
    /**
     * Generated from protobuf enum <code>FLOWTYPE_WAP = 3;</code>
     */
    const FLOWTYPE_WAP = 3;

    private static $valueToName = [
        self::UNKNOWN_FLOWTYPE => 'UNKNOWN_FLOWTYPE',
        self::FLOWTYPE_APP => 'FLOWTYPE_APP',
        self::FLOWTYPE_PC => 'FLOWTYPE_PC',
        self::FLOWTYPE_WAP => 'FLOWTYPE_WAP',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

