<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ad.GetBalanceRequest</code>
 */
class GetBalanceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 advertiser_id = 1;</code>
     */
    private $advertiser_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $advertiser_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RawAd::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 advertiser_id = 1;</code>
     * @return int
     */
    public function getAdvertiserId()
    {
        return $this->advertiser_id;
    }

    /**
     * Generated from protobuf field <code>int32 advertiser_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAdvertiserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->advertiser_id = $var;

        return $this;
    }

}

