<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ad.GlobalAdObject</code>
 */
class GlobalAdObject extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ad_id = 1;</code>
     */
    private $ad_id = '';
    /**
     * Generated from protobuf field <code>string ad_name = 2;</code>
     */
    private $ad_name = '';
    /**
     * Generated from protobuf field <code>string order_id = 3;</code>
     */
    private $order_id = '';
    /**
     * Generated from protobuf field <code>.ad.Information information = 4;</code>
     */
    private $information = 0;
    /**
     * Generated from protobuf field <code>string ad_url = 5;</code>
     */
    private $ad_url = '';
    /**
     * Generated from protobuf field <code>int64 ad_throw_num = 6;</code>
     */
    private $ad_throw_num = 0;
    /**
     * Generated from protobuf field <code>repeated .ad.TimeObject time = 7;</code>
     */
    private $time;
    /**
     * Generated from protobuf field <code>string monitor_urls = 8;</code>
     */
    private $monitor_urls = '';
    /**
     * Generated from protobuf field <code>string monitor_pv_urls = 9;</code>
     */
    private $monitor_pv_urls = '';
    /**
     * Generated from protobuf field <code>.ad.MPlay m_play = 10;</code>
     */
    private $m_play = 0;
    /**
     * Generated from protobuf field <code>repeated int32 provinces = 11 [packed = true];</code>
     */
    private $provinces;
    /**
     * Generated from protobuf field <code>.ad.MonitorType monitor_type = 12;</code>
     */
    private $monitor_type = 0;
    /**
     * Generated from protobuf field <code>int64 amount_investment = 15;</code>
     */
    private $amount_investment = 0;
    /**
     * Generated from protobuf field <code>float bidding = 16;</code>
     */
    private $bidding = 0.0;
    /**
     * Generated from protobuf field <code>.ad.Carousel carousel = 17;</code>
     */
    private $carousel = 0;
    /**
     * Generated from protobuf field <code>map<string, int64> plan_by_date = 18;</code>
     */
    private $plan_by_date;
    /**
     * Generated from protobuf field <code>.ad.Distribution plan_day_type = 19;</code>
     */
    private $plan_day_type = 0;
    /**
     * Generated from protobuf field <code>.ad.Distribution plan_hour_type = 20;</code>
     */
    private $plan_hour_type = 0;
    /**
     * Generated from protobuf field <code>.ad.CreateType create_type = 21;</code>
     */
    private $create_type = 0;
    /**
     * Generated from protobuf field <code>.ad.AdFrom ad_from = 22;</code>
     */
    private $ad_from = 0;
    /**
     * Generated from protobuf field <code>.ad.JumpType jump_type = 23;</code>
     */
    private $jump_type = 0;
    /**
     * string spread_name = 24;
     *
     * Generated from protobuf field <code>string union_ad_place_id = 25;</code>
     */
    private $union_ad_place_id = '';
    /**
     * Generated from protobuf field <code>string union_ad_js = 26;</code>
     */
    private $union_ad_js = '';
    /**
     * Generated from protobuf field <code>int32 union_ad_width = 27;</code>
     */
    private $union_ad_width = 0;
    /**
     * Generated from protobuf field <code>int32 union_ad_height = 28;</code>
     */
    private $union_ad_height = 0;
    /**
     * Generated from protobuf field <code>string apk_name = 29;</code>
     */
    private $apk_name = '';
    /**
     * Generated from protobuf field <code>repeated .ad.NetworkWay network_way = 30 [packed = true];</code>
     */
    private $network_way;
    /**
     * Generated from protobuf field <code>repeated .ad.Operator operator = 31 [packed = true];</code>
     */
    private $operator;
    /**
     * Generated from protobuf field <code>repeated .ad.MediaID media_ids = 32 [packed = true];</code>
     */
    private $media_ids;
    /**
     *bool is_oriented = 33;
     *
     * Generated from protobuf field <code>repeated int32 version_oriented = 34 [packed = true];</code>
     */
    private $version_oriented;
    /**
     *bool is_black_white = 35;
     *
     * Generated from protobuf field <code>repeated .ad.MaterialObject materials = 36;</code>
     */
    private $materials;
    /**
     * Generated from protobuf field <code>int32 advertiser_id = 37;</code>
     */
    private $advertiser_id = 0;
    /**
     * Generated from protobuf field <code>int64 throw_num = 38;</code>
     */
    private $throw_num = 0;
    /**
     *int32 channel = 39;
     *int32 ad_id_code = 40;
     *int32 position_type = 41;
     *int32 location_id = 42;
     * int32 cpm_bid_floor = 43;
     * int32 cpc_bid_floor = 44;
     *float discount = 45;
     * float coefficient = 46;
     *
     * Generated from protobuf field <code>string payment = 47;</code>
     */
    private $payment = '';
    /**
     * Generated from protobuf field <code>string black_white_redis_key = 48;</code>
     */
    private $black_white_redis_key = '';
    /**
     * string ad_content = 49;
     *
     * Generated from protobuf field <code>repeated .ad.GlobalAdObject.PotentialPlace position = 50;</code>
     */
    private $position;
    /**
     * Generated from protobuf field <code>.ad.PlatformType platform_type = 51;</code>
     */
    private $platform_type = 0;
    /**
     * Generated from protobuf field <code>int32 cpm_num = 52;</code>
     */
    private $cpm_num = 0;
    /**
     * Generated from protobuf field <code>int32 click_num = 53;</code>
     */
    private $click_num = 0;
    /**
     * int32 width = 54;
     * int32 height = 55;
     *
     * Generated from protobuf field <code>map<string, string> annotations = 56;</code>
     */
    private $annotations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ad_id
     *     @type string $ad_name
     *     @type string $order_id
     *     @type int $information
     *     @type string $ad_url
     *     @type int|string $ad_throw_num
     *     @type \Ad\TimeObject[]|\Google\Protobuf\Internal\RepeatedField $time
     *     @type string $monitor_urls
     *     @type string $monitor_pv_urls
     *     @type int $m_play
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $provinces
     *     @type int $monitor_type
     *     @type int|string $amount_investment
     *     @type float $bidding
     *     @type int $carousel
     *     @type array|\Google\Protobuf\Internal\MapField $plan_by_date
     *     @type int $plan_day_type
     *     @type int $plan_hour_type
     *     @type int $create_type
     *     @type int $ad_from
     *     @type int $jump_type
     *     @type string $union_ad_place_id
     *           string spread_name = 24;
     *     @type string $union_ad_js
     *     @type int $union_ad_width
     *     @type int $union_ad_height
     *     @type string $apk_name
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $network_way
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $operator
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $media_ids
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $version_oriented
     *          bool is_oriented = 33;
     *     @type \Ad\MaterialObject[]|\Google\Protobuf\Internal\RepeatedField $materials
     *          bool is_black_white = 35;
     *     @type int $advertiser_id
     *     @type int|string $throw_num
     *     @type string $payment
     *          int32 channel = 39;
     *          int32 ad_id_code = 40;
     *          int32 position_type = 41;
     *          int32 location_id = 42;
     *           int32 cpm_bid_floor = 43;
     *           int32 cpc_bid_floor = 44;
     *          float discount = 45;
     *           float coefficient = 46;
     *     @type string $black_white_redis_key
     *     @type \Ad\GlobalAdObject\PotentialPlace[]|\Google\Protobuf\Internal\RepeatedField $position
     *           string ad_content = 49;
     *     @type int $platform_type
     *     @type int $cpm_num
     *     @type int $click_num
     *     @type array|\Google\Protobuf\Internal\MapField $annotations
     *           int32 width = 54;
     *           int32 height = 55;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RawAd::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ad_id = 1;</code>
     * @return string
     */
    public function getAdId()
    {
        return $this->ad_id;
    }

    /**
     * Generated from protobuf field <code>string ad_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAdId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ad_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ad_name = 2;</code>
     * @return string
     */
    public function getAdName()
    {
        return $this->ad_name;
    }

    /**
     * Generated from protobuf field <code>string ad_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAdName($var)
    {
        GPBUtil::checkString($var, True);
        $this->ad_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_id = 3;</code>
     * @return string
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     * Generated from protobuf field <code>string order_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ad.Information information = 4;</code>
     * @return int
     */
    public function getInformation()
    {
        return $this->information;
    }

    /**
     * Generated from protobuf field <code>.ad.Information information = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setInformation($var)
    {
        GPBUtil::checkEnum($var, \Ad\Information::class);
        $this->information = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ad_url = 5;</code>
     * @return string
     */
    public function getAdUrl()
    {
        return $this->ad_url;
    }

    /**
     * Generated from protobuf field <code>string ad_url = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAdUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->ad_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ad_throw_num = 6;</code>
     * @return int|string
     */
    public function getAdThrowNum()
    {
        return $this->ad_throw_num;
    }

    /**
     * Generated from protobuf field <code>int64 ad_throw_num = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAdThrowNum($var)
    {
        GPBUtil::checkInt64($var);
        $this->ad_throw_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ad.TimeObject time = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>repeated .ad.TimeObject time = 7;</code>
     * @param \Ad\TimeObject[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTime($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ad\TimeObject::class);
        $this->time = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string monitor_urls = 8;</code>
     * @return string
     */
    public function getMonitorUrls()
    {
        return $this->monitor_urls;
    }

    /**
     * Generated from protobuf field <code>string monitor_urls = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMonitorUrls($var)
    {
        GPBUtil::checkString($var, True);
        $this->monitor_urls = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string monitor_pv_urls = 9;</code>
     * @return string
     */
    public function getMonitorPvUrls()
    {
        return $this->monitor_pv_urls;
    }

    /**
     * Generated from protobuf field <code>string monitor_pv_urls = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setMonitorPvUrls($var)
    {
        GPBUtil::checkString($var, True);
        $this->monitor_pv_urls = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ad.MPlay m_play = 10;</code>
     * @return int
     */
    public function getMPlay()
    {
        return $this->m_play;
    }

    /**
     * Generated from protobuf field <code>.ad.MPlay m_play = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setMPlay($var)
    {
        GPBUtil::checkEnum($var, \Ad\MPlay::class);
        $this->m_play = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 provinces = 11 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProvinces()
    {
        return $this->provinces;
    }

    /**
     * Generated from protobuf field <code>repeated int32 provinces = 11 [packed = true];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProvinces($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->provinces = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ad.MonitorType monitor_type = 12;</code>
     * @return int
     */
    public function getMonitorType()
    {
        return $this->monitor_type;
    }

    /**
     * Generated from protobuf field <code>.ad.MonitorType monitor_type = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setMonitorType($var)
    {
        GPBUtil::checkEnum($var, \Ad\MonitorType::class);
        $this->monitor_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 amount_investment = 15;</code>
     * @return int|string
     */
    public function getAmountInvestment()
    {
        return $this->amount_investment;
    }

    /**
     * Generated from protobuf field <code>int64 amount_investment = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmountInvestment($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount_investment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float bidding = 16;</code>
     * @return float
     */
    public function getBidding()
    {
        return $this->bidding;
    }

    /**
     * Generated from protobuf field <code>float bidding = 16;</code>
     * @param float $var
     * @return $this
     */
    public function setBidding($var)
    {
        GPBUtil::checkFloat($var);
        $this->bidding = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ad.Carousel carousel = 17;</code>
     * @return int
     */
    public function getCarousel()
    {
        return $this->carousel;
    }

    /**
     * Generated from protobuf field <code>.ad.Carousel carousel = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setCarousel($var)
    {
        GPBUtil::checkEnum($var, \Ad\Carousel::class);
        $this->carousel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, int64> plan_by_date = 18;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getPlanByDate()
    {
        return $this->plan_by_date;
    }

    /**
     * Generated from protobuf field <code>map<string, int64> plan_by_date = 18;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setPlanByDate($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT64);
        $this->plan_by_date = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ad.Distribution plan_day_type = 19;</code>
     * @return int
     */
    public function getPlanDayType()
    {
        return $this->plan_day_type;
    }

    /**
     * Generated from protobuf field <code>.ad.Distribution plan_day_type = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setPlanDayType($var)
    {
        GPBUtil::checkEnum($var, \Ad\Distribution::class);
        $this->plan_day_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ad.Distribution plan_hour_type = 20;</code>
     * @return int
     */
    public function getPlanHourType()
    {
        return $this->plan_hour_type;
    }

    /**
     * Generated from protobuf field <code>.ad.Distribution plan_hour_type = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setPlanHourType($var)
    {
        GPBUtil::checkEnum($var, \Ad\Distribution::class);
        $this->plan_hour_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ad.CreateType create_type = 21;</code>
     * @return int
     */
    public function getCreateType()
    {
        return $this->create_type;
    }

    /**
     * Generated from protobuf field <code>.ad.CreateType create_type = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setCreateType($var)
    {
        GPBUtil::checkEnum($var, \Ad\CreateType::class);
        $this->create_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ad.AdFrom ad_from = 22;</code>
     * @return int
     */
    public function getAdFrom()
    {
        return $this->ad_from;
    }

    /**
     * Generated from protobuf field <code>.ad.AdFrom ad_from = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setAdFrom($var)
    {
        GPBUtil::checkEnum($var, \Ad\AdFrom::class);
        $this->ad_from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ad.JumpType jump_type = 23;</code>
     * @return int
     */
    public function getJumpType()
    {
        return $this->jump_type;
    }

    /**
     * Generated from protobuf field <code>.ad.JumpType jump_type = 23;</code>
     * @param int $var
     * @return $this
     */
    public function setJumpType($var)
    {
        GPBUtil::checkEnum($var, \Ad\JumpType::class);
        $this->jump_type = $var;

        return $this;
    }

    /**
     * string spread_name = 24;
     *
     * Generated from protobuf field <code>string union_ad_place_id = 25;</code>
     * @return string
     */
    public function getUnionAdPlaceId()
    {
        return $this->union_ad_place_id;
    }

    /**
     * string spread_name = 24;
     *
     * Generated from protobuf field <code>string union_ad_place_id = 25;</code>
     * @param string $var
     * @return $this
     */
    public function setUnionAdPlaceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->union_ad_place_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string union_ad_js = 26;</code>
     * @return string
     */
    public function getUnionAdJs()
    {
        return $this->union_ad_js;
    }

    /**
     * Generated from protobuf field <code>string union_ad_js = 26;</code>
     * @param string $var
     * @return $this
     */
    public function setUnionAdJs($var)
    {
        GPBUtil::checkString($var, True);
        $this->union_ad_js = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 union_ad_width = 27;</code>
     * @return int
     */
    public function getUnionAdWidth()
    {
        return $this->union_ad_width;
    }

    /**
     * Generated from protobuf field <code>int32 union_ad_width = 27;</code>
     * @param int $var
     * @return $this
     */
    public function setUnionAdWidth($var)
    {
        GPBUtil::checkInt32($var);
        $this->union_ad_width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 union_ad_height = 28;</code>
     * @return int
     */
    public function getUnionAdHeight()
    {
        return $this->union_ad_height;
    }

    /**
     * Generated from protobuf field <code>int32 union_ad_height = 28;</code>
     * @param int $var
     * @return $this
     */
    public function setUnionAdHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->union_ad_height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string apk_name = 29;</code>
     * @return string
     */
    public function getApkName()
    {
        return $this->apk_name;
    }

    /**
     * Generated from protobuf field <code>string apk_name = 29;</code>
     * @param string $var
     * @return $this
     */
    public function setApkName($var)
    {
        GPBUtil::checkString($var, True);
        $this->apk_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ad.NetworkWay network_way = 30 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNetworkWay()
    {
        return $this->network_way;
    }

    /**
     * Generated from protobuf field <code>repeated .ad.NetworkWay network_way = 30 [packed = true];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNetworkWay($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Ad\NetworkWay::class);
        $this->network_way = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ad.Operator operator = 31 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOperator()
    {
        return $this->operator;
    }

    /**
     * Generated from protobuf field <code>repeated .ad.Operator operator = 31 [packed = true];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOperator($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Ad\Operator::class);
        $this->operator = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ad.MediaID media_ids = 32 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMediaIds()
    {
        return $this->media_ids;
    }

    /**
     * Generated from protobuf field <code>repeated .ad.MediaID media_ids = 32 [packed = true];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMediaIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Ad\MediaID::class);
        $this->media_ids = $arr;

        return $this;
    }

    /**
     *bool is_oriented = 33;
     *
     * Generated from protobuf field <code>repeated int32 version_oriented = 34 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVersionOriented()
    {
        return $this->version_oriented;
    }

    /**
     *bool is_oriented = 33;
     *
     * Generated from protobuf field <code>repeated int32 version_oriented = 34 [packed = true];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVersionOriented($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->version_oriented = $arr;

        return $this;
    }

    /**
     *bool is_black_white = 35;
     *
     * Generated from protobuf field <code>repeated .ad.MaterialObject materials = 36;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMaterials()
    {
        return $this->materials;
    }

    /**
     *bool is_black_white = 35;
     *
     * Generated from protobuf field <code>repeated .ad.MaterialObject materials = 36;</code>
     * @param \Ad\MaterialObject[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMaterials($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ad\MaterialObject::class);
        $this->materials = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 advertiser_id = 37;</code>
     * @return int
     */
    public function getAdvertiserId()
    {
        return $this->advertiser_id;
    }

    /**
     * Generated from protobuf field <code>int32 advertiser_id = 37;</code>
     * @param int $var
     * @return $this
     */
    public function setAdvertiserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->advertiser_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 throw_num = 38;</code>
     * @return int|string
     */
    public function getThrowNum()
    {
        return $this->throw_num;
    }

    /**
     * Generated from protobuf field <code>int64 throw_num = 38;</code>
     * @param int|string $var
     * @return $this
     */
    public function setThrowNum($var)
    {
        GPBUtil::checkInt64($var);
        $this->throw_num = $var;

        return $this;
    }

    /**
     *int32 channel = 39;
     *int32 ad_id_code = 40;
     *int32 position_type = 41;
     *int32 location_id = 42;
     * int32 cpm_bid_floor = 43;
     * int32 cpc_bid_floor = 44;
     *float discount = 45;
     * float coefficient = 46;
     *
     * Generated from protobuf field <code>string payment = 47;</code>
     * @return string
     */
    public function getPayment()
    {
        return $this->payment;
    }

    /**
     *int32 channel = 39;
     *int32 ad_id_code = 40;
     *int32 position_type = 41;
     *int32 location_id = 42;
     * int32 cpm_bid_floor = 43;
     * int32 cpc_bid_floor = 44;
     *float discount = 45;
     * float coefficient = 46;
     *
     * Generated from protobuf field <code>string payment = 47;</code>
     * @param string $var
     * @return $this
     */
    public function setPayment($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string black_white_redis_key = 48;</code>
     * @return string
     */
    public function getBlackWhiteRedisKey()
    {
        return $this->black_white_redis_key;
    }

    /**
     * Generated from protobuf field <code>string black_white_redis_key = 48;</code>
     * @param string $var
     * @return $this
     */
    public function setBlackWhiteRedisKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->black_white_redis_key = $var;

        return $this;
    }

    /**
     * string ad_content = 49;
     *
     * Generated from protobuf field <code>repeated .ad.GlobalAdObject.PotentialPlace position = 50;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * string ad_content = 49;
     *
     * Generated from protobuf field <code>repeated .ad.GlobalAdObject.PotentialPlace position = 50;</code>
     * @param \Ad\GlobalAdObject\PotentialPlace[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPosition($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ad\GlobalAdObject\PotentialPlace::class);
        $this->position = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ad.PlatformType platform_type = 51;</code>
     * @return int
     */
    public function getPlatformType()
    {
        return $this->platform_type;
    }

    /**
     * Generated from protobuf field <code>.ad.PlatformType platform_type = 51;</code>
     * @param int $var
     * @return $this
     */
    public function setPlatformType($var)
    {
        GPBUtil::checkEnum($var, \Ad\PlatformType::class);
        $this->platform_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cpm_num = 52;</code>
     * @return int
     */
    public function getCpmNum()
    {
        return $this->cpm_num;
    }

    /**
     * Generated from protobuf field <code>int32 cpm_num = 52;</code>
     * @param int $var
     * @return $this
     */
    public function setCpmNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->cpm_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 click_num = 53;</code>
     * @return int
     */
    public function getClickNum()
    {
        return $this->click_num;
    }

    /**
     * Generated from protobuf field <code>int32 click_num = 53;</code>
     * @param int $var
     * @return $this
     */
    public function setClickNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->click_num = $var;

        return $this;
    }

    /**
     * int32 width = 54;
     * int32 height = 55;
     *
     * Generated from protobuf field <code>map<string, string> annotations = 56;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAnnotations()
    {
        return $this->annotations;
    }

    /**
     * int32 width = 54;
     * int32 height = 55;
     *
     * Generated from protobuf field <code>map<string, string> annotations = 56;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAnnotations($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->annotations = $arr;

        return $this;
    }

}

