<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

if (false) {
    /**
     * This class is deprecated. Use Ad\GlobalAdObject\PotentialPlace instead.
     * @deprecated
     */
    class GlobalAdObject_PotentialPlace {}
}
class_exists(GlobalAdObject\PotentialPlace::class);
@trigger_error('Ad\GlobalAdObject_PotentialPlace is deprecated and will be removed in the next major release. Use Ad\GlobalAdObject\PotentialPlace instead', E_USER_DEPRECATED);

