<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *通投广告返回体
 *
 * Generated from protobuf message <code>ad.GlobalReply</code>
 */
class GlobalReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .ad.GlobalAdObject global_data = 1;</code>
     */
    private $global_data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ad\GlobalAdObject[]|\Google\Protobuf\Internal\RepeatedField $global_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RawAd::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .ad.GlobalAdObject global_data = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGlobalData()
    {
        return $this->global_data;
    }

    /**
     * Generated from protobuf field <code>repeated .ad.GlobalAdObject global_data = 1;</code>
     * @param \Ad\GlobalAdObject[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGlobalData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ad\GlobalAdObject::class);
        $this->global_data = $arr;

        return $this;
    }

}

