<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use UnexpectedValueException;

/**
 * Protobuf type <code>ad.Information</code>
 */
class Information
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_INFOMATION = 0;</code>
     */
    const UNKNOWN_INFOMATION = 0;
    /**
     * Generated from protobuf enum <code>SMALL = 1;</code>
     */
    const SMALL = 1;
    /**
     * Generated from protobuf enum <code>GROUP = 2;</code>
     */
    const GROUP = 2;
    /**
     * Generated from protobuf enum <code>BIG = 3;</code>
     */
    const BIG = 3;

    private static $valueToName = [
        self::UNKNOWN_INFOMATION => 'UNKNOWN_INFOMATION',
        self::SMALL => 'SMALL',
        self::GROUP => 'GROUP',
        self::BIG => 'BIG',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

