<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use UnexpectedValueException;

/**
 * Protobuf type <code>ad.JumpType</code>
 */
class JumpType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_JUMPTYPE = 0;</code>
     */
    const UNKNOWN_JUMPTYPE = 0;
    /**
     * Generated from protobuf enum <code>CLICK = 1;</code>
     */
    const CLICK = 1;
    /**
     * Generated from protobuf enum <code>APK_DOWNLOAD = 2;</code>
     */
    const APK_DOWNLOAD = 2;

    private static $valueToName = [
        self::UNKNOWN_JUMPTYPE => 'UNKNOWN_JUMPTYPE',
        self::CLICK => 'CLICK',
        self::APK_DOWNLOAD => 'APK_DOWNLOAD',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

