<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ad.MaterialObject</code>
 */
class MaterialObject extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string path = 1;</code>
     */
    private $path = '';
    /**
     * Generated from protobuf field <code>string ad_title = 2;</code>
     */
    private $ad_title = '';
    /**
     * Generated from protobuf field <code>int32 group = 3;</code>
     */
    private $group = 0;
    /**
     * Generated from protobuf field <code>string group_id = 4;</code>
     */
    private $group_id = '';
    /**
     * Generated from protobuf field <code>int32 width = 5;</code>
     */
    private $width = 0;
    /**
     * Generated from protobuf field <code>int32 height = 6;</code>
     */
    private $height = 0;
    /**
     * Generated from protobuf field <code>string spread_name = 7;</code>
     */
    private $spread_name = '';
    /**
     * Generated from protobuf field <code>map<string, string> annotations = 8;</code>
     */
    private $annotations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *     @type string $ad_title
     *     @type int $group
     *     @type string $group_id
     *     @type int $width
     *     @type int $height
     *     @type string $spread_name
     *     @type array|\Google\Protobuf\Internal\MapField $annotations
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RawAd::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ad_title = 2;</code>
     * @return string
     */
    public function getAdTitle()
    {
        return $this->ad_title;
    }

    /**
     * Generated from protobuf field <code>string ad_title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAdTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->ad_title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 group = 3;</code>
     * @return int
     */
    public function getGroup()
    {
        return $this->group;
    }

    /**
     * Generated from protobuf field <code>int32 group = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setGroup($var)
    {
        GPBUtil::checkInt32($var);
        $this->group = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string group_id = 4;</code>
     * @return string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * Generated from protobuf field <code>string group_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 width = 5;</code>
     * @return int
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * Generated from protobuf field <code>int32 width = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkInt32($var);
        $this->width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 height = 6;</code>
     * @return int
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int32 height = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string spread_name = 7;</code>
     * @return string
     */
    public function getSpreadName()
    {
        return $this->spread_name;
    }

    /**
     * Generated from protobuf field <code>string spread_name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSpreadName($var)
    {
        GPBUtil::checkString($var, True);
        $this->spread_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> annotations = 8;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAnnotations()
    {
        return $this->annotations;
    }

    /**
     * Generated from protobuf field <code>map<string, string> annotations = 8;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAnnotations($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->annotations = $arr;

        return $this;
    }

}

