<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use UnexpectedValueException;

/**
 * Protobuf type <code>ad.MediaID</code>
 */
class MediaID
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_MEDIAID = 0;</code>
     */
    const UNKNOWN_MEDIAID = 0;
    /**
     * Generated from protobuf enum <code>IOS = 1;</code>
     */
    const IOS = 1;
    /**
     * Generated from protobuf enum <code>HUAWEI = 2;</code>
     */
    const HUAWEI = 2;
    /**
     * Generated from protobuf enum <code>XIOAMI = 3;</code>
     */
    const XIOAMI = 3;
    /**
     * Generated from protobuf enum <code>SAMSUNG = 4;</code>
     */
    const SAMSUNG = 4;
    /**
     * Generated from protobuf enum <code>JINLI = 5;</code>
     */
    const JINLI = 5;
    /**
     * Generated from protobuf enum <code>KUPAI = 6;</code>
     */
    const KUPAI = 6;
    /**
     * Generated from protobuf enum <code>OPPO = 7;</code>
     */
    const OPPO = 7;
    /**
     * Generated from protobuf enum <code>VIVO = 8;</code>
     */
    const VIVO = 8;
    /**
     * Generated from protobuf enum <code>MEIZU = 9;</code>
     */
    const MEIZU = 9;
    /**
     * Generated from protobuf enum <code>LENOVO = 10;</code>
     */
    const LENOVO = 10;
    /**
     * Generated from protobuf enum <code>LESHI = 11;</code>
     */
    const LESHI = 11;
    /**
     * Generated from protobuf enum <code>ZHONGXING = 12;</code>
     */
    const ZHONGXING = 12;
    /**
     * Generated from protobuf enum <code>NOKIA = 13;</code>
     */
    const NOKIA = 13;
    /**
     * Generated from protobuf enum <code>HTC = 14;</code>
     */
    const HTC = 14;
    /**
     * Generated from protobuf enum <code>XIAOLAJIAO = 15;</code>
     */
    const XIAOLAJIAO = 15;
    /**
     * Generated from protobuf enum <code>NUBIYA = 16;</code>
     */
    const NUBIYA = 16;
    /**
     * Generated from protobuf enum <code>HAXIN = 17;</code>
     */
    const HAXIN = 17;
    /**
     * Generated from protobuf enum <code>TCL = 18;</code>
     */
    const TCL = 18;
    /**
     * Generated from protobuf enum <code>SONY = 19;</code>
     */
    const SONY = 19;

    private static $valueToName = [
        self::UNKNOWN_MEDIAID => 'UNKNOWN_MEDIAID',
        self::IOS => 'IOS',
        self::HUAWEI => 'HUAWEI',
        self::XIOAMI => 'XIOAMI',
        self::SAMSUNG => 'SAMSUNG',
        self::JINLI => 'JINLI',
        self::KUPAI => 'KUPAI',
        self::OPPO => 'OPPO',
        self::VIVO => 'VIVO',
        self::MEIZU => 'MEIZU',
        self::LENOVO => 'LENOVO',
        self::LESHI => 'LESHI',
        self::ZHONGXING => 'ZHONGXING',
        self::NOKIA => 'NOKIA',
        self::HTC => 'HTC',
        self::XIAOLAJIAO => 'XIAOLAJIAO',
        self::NUBIYA => 'NUBIYA',
        self::HAXIN => 'HAXIN',
        self::TCL => 'TCL',
        self::SONY => 'SONY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

