<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use UnexpectedValueException;

/**
 * Protobuf type <code>ad.MonitorType</code>
 */
class MonitorType
{
    /**
     * Generated from protobuf enum <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * Generated from protobuf enum <code>MIAOZHEN = 1;</code>
     */
    const MIAOZHEN = 1;
    /**
     * Generated from protobuf enum <code>ADMASTER = 2;</code>
     */
    const ADMASTER = 2;
    /**
     * Generated from protobuf enum <code>REYUN = 3;</code>
     */
    const REYUN = 3;
    /**
     * Generated from protobuf enum <code>TALKINGDATA = 4;</code>
     */
    const TALKINGDATA = 4;

    private static $valueToName = [
        self::NONE => 'NONE',
        self::MIAOZHEN => 'MIAOZHEN',
        self::ADMASTER => 'ADMASTER',
        self::REYUN => 'REYUN',
        self::TALKINGDATA => 'TALKINGDATA',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

