<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use UnexpectedValueException;

/**
 * Protobuf type <code>ad.MPlay</code>
 */
class MPlay
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_MPLAY = 0;</code>
     */
    const UNKNOWN_MPLAY = 0;
    /**
     * Generated from protobuf enum <code>DAY_ROLL = 1;</code>
     */
    const DAY_ROLL = 1;
    /**
     * Generated from protobuf enum <code>MATERIAL_ROLL = 2;</code>
     */
    const MATERIAL_ROLL = 2;

    private static $valueToName = [
        self::UNKNOWN_MPLAY => 'UNKNOWN_MPLAY',
        self::DAY_ROLL => 'DAY_ROLL',
        self::MATERIAL_ROLL => 'MATERIAL_ROLL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

