<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use UnexpectedValueException;

/**
 * Protobuf type <code>ad.NetworkWay</code>
 */
class NetworkWay
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_NETWORKWAY = 0;</code>
     */
    const UNKNOWN_NETWORKWAY = 0;
    /**
     * Generated from protobuf enum <code>WIFI = 1;</code>
     */
    const WIFI = 1;
    /**
     * Generated from protobuf enum <code>_4G = 2;</code>
     */
    const _4G = 2;
    /**
     * Generated from protobuf enum <code>_3G = 3;</code>
     */
    const _3G = 3;
    /**
     * Generated from protobuf enum <code>_2G = 4;</code>
     */
    const _2G = 4;

    private static $valueToName = [
        self::UNKNOWN_NETWORKWAY => 'UNKNOWN_NETWORKWAY',
        self::WIFI => 'WIFI',
        self::_4G => '_4G',
        self::_3G => '_3G',
        self::_2G => '_2G',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

