<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use UnexpectedValueException;

/**
 * Protobuf type <code>ad.Operator</code>
 */
class Operator
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_OPERATOR = 0;</code>
     */
    const UNKNOWN_OPERATOR = 0;
    /**
     * Generated from protobuf enum <code>UNICOM = 1;</code>
     */
    const UNICOM = 1;
    /**
     * Generated from protobuf enum <code>MOBILE = 2;</code>
     */
    const MOBILE = 2;
    /**
     * Generated from protobuf enum <code>TELECOM = 3;</code>
     */
    const TELECOM = 3;

    private static $valueToName = [
        self::UNKNOWN_OPERATOR => 'UNKNOWN_OPERATOR',
        self::UNICOM => 'UNICOM',
        self::MOBILE => 'MOBILE',
        self::TELECOM => 'TELECOM',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

