<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use UnexpectedValueException;

/**
 * Protobuf type <code>ad.PlaceAttribute</code>
 */
class PlaceAttribute
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_PLACEATTRIBUTE = 0;</code>
     */
    const UNKNOWN_PLACEATTRIBUTE = 0;
    /**
     * Generated from protobuf enum <code>KAIPING = 1;</code>
     */
    const KAIPING = 1;
    /**
     * Generated from protobuf enum <code>XINXILIU = 2;</code>
     */
    const XINXILIU = 2;
    /**
     * Generated from protobuf enum <code>BANNER = 3;</code>
     */
    const BANNER = 3;
    /**
     * Generated from protobuf enum <code>CHAPING = 4;</code>
     */
    const CHAPING = 4;
    /**
     * Generated from protobuf enum <code>QIANRU = 5;</code>
     */
    const QIANRU = 5;
    /**
     * Generated from protobuf enum <code>TU = 6;</code>
     */
    const TU = 6;
    /**
     * Generated from protobuf enum <code>XUANFU = 7;</code>
     */
    const XUANFU = 7;
    /**
     * Generated from protobuf enum <code>WENZILIAN = 8;</code>
     */
    const WENZILIAN = 8;
    /**
     * Generated from protobuf enum <code>HENGFU = 9;</code>
     */
    const HENGFU = 9;

    private static $valueToName = [
        self::UNKNOWN_PLACEATTRIBUTE => 'UNKNOWN_PLACEATTRIBUTE',
        self::KAIPING => 'KAIPING',
        self::XINXILIU => 'XINXILIU',
        self::BANNER => 'BANNER',
        self::CHAPING => 'CHAPING',
        self::QIANRU => 'QIANRU',
        self::TU => 'TU',
        self::XUANFU => 'XUANFU',
        self::WENZILIAN => 'WENZILIAN',
        self::HENGFU => 'HENGFU',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

