<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

use UnexpectedValueException;

/**
 *投放终端
 *
 * Protobuf type <code>ad.PortType</code>
 */
class PortType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_PORTTYPE = 0;</code>
     */
    const UNKNOWN_PORTTYPE = 0;
    /**
     * Generated from protobuf enum <code>PORTTYPE_IOS = 1;</code>
     */
    const PORTTYPE_IOS = 1;
    /**
     * Generated from protobuf enum <code>PORTTYPE_ANDROID = 2;</code>
     */
    const PORTTYPE_ANDROID = 2;
    /**
     * Generated from protobuf enum <code>PORTTYPE_PC = 3;</code>
     */
    const PORTTYPE_PC = 3;
    /**
     * Generated from protobuf enum <code>PORTTYPE_WAP = 4;</code>
     */
    const PORTTYPE_WAP = 4;
    /**
     * Generated from protobuf enum <code>PORTTYPE_DESKTOP_CLIENT = 5;</code>
     */
    const PORTTYPE_DESKTOP_CLIENT = 5;

    private static $valueToName = [
        self::UNKNOWN_PORTTYPE => 'UNKNOWN_PORTTYPE',
        self::PORTTYPE_IOS => 'PORTTYPE_IOS',
        self::PORTTYPE_ANDROID => 'PORTTYPE_ANDROID',
        self::PORTTYPE_PC => 'PORTTYPE_PC',
        self::PORTTYPE_WAP => 'PORTTYPE_WAP',
        self::PORTTYPE_DESKTOP_CLIENT => 'PORTTYPE_DESKTOP_CLIENT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

