<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rawAd.proto

namespace Ad;

if (false) {
    /**
     * This class is deprecated. Use Ad\TimeObject\Time instead.
     * @deprecated
     */
    class TimeObject_Time {}
}
class_exists(TimeObject\Time::class);
@trigger_error('Ad\TimeObject_Time is deprecated and will be removed in the next major release. Use Ad\TimeObject\Time instead', E_USER_DEPRECATED);

